version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18.15.0
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm install -g @angular/cli
      - run: npm i primeng primeicons
      - run: npm run build -- --prod
      - run: ng test