version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm ci
      - run: sudo npm install -g @angular/cli
      - run: ng build --configuration=production

  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm ci
      - run: sudo npm install -g @angular/cli
      - run: ng test --watch=false
    environment:
      CHROME_BIN: /usr/bin/google-chrome

  deploy:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm ci
      - run: sudo npm i -g vercel@latest
      - run: vercel --prod --name front-end-voip --token $VERCEL_TOKEN

workflows:
  build-and-test:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: main