version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm install -g @angular/cli
      - run: npm i primeng primeicons
      - run: npm run build -- --prod
      - run: ng test
      - deploy:
          name: Deploy to Production
          command: |
            npm run deploy-prod