version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm ci
      - run: npm install -g @angular/cli
      - run: ng build --prod
  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm ci
      - run: npm install -g @angular/cli
      - run: ng test --watch=false